### ISSUE TITLE
[BUG] OpenAPI UI doesn't apply Authorization header present in the spec

### ISSUE THREAD

**Issue by coderfromhere** [biocad/openapi3#29]
Hi,

This is a cross-post of https://github.com/biocad/openapi3/issues/29 as I'm not sure which package causes the issue.

below is a sample UI interface that seems to ignore the defined "Authroization" request header and requests fail with expected 401 errors (also see the incomplete curl snippet)
![Screen Shot 2021-09-28 at 17 00 59](https://user-images.githubusercontent.com/59691490/135123614-ed02cc71-b77c-4917-9057-f17d017193e0.png)

A frozen packages snapshot contains:
```
openapi3 ==3.1.0
servant-openapi3 ==2.0.1.2
servant-server ==0.18.2
servant-swagger-ui ==0.3.5.3.47.1
servant-swagger-ui-core ==0.3.5
```

**Comment by stevladimir** [comment]
It's "bug" in the openapi spec: https://spec.openapis.org/oas/v3.1.0.html#fixed-fields-9

For authentication you should use `security` section instead

**Comment by coderfromhere** [comment]
oh, thanks for pointing at the spec section! Let me verify that it works as intended once I add it, and then I'll close the issue.

**Comment by maksbotan** [comment]
Hi,

Thanks for the report. As @stevladimir mentioned, `Authorization` should be handled through corresponding mechanism in OpenAPI, not with per-path headers. Look for "security schemes" and "security requirements" in the spec and in this package.

I will close this as there is nothing I can do on the library's part. If you run into problems with defining security schemes, please open a new issue.

**Comment by coderfromhere** [comment]
@maksbotan Hi!

I'd like to clarify whether defining security schemes for `OpenAPI` values is just enought to enable authorization headers in UI requests to respective endpoints, or is it also a requirement to remove existing "Authorization" headers from endp[oint definitions?

I've got this security schema applied:

```haskell
openApiSpec :: OpenApi
openApiSpec =
    -- Combine 'Public' spec
    toOpenApi publicSpec
    <>
    -- with JWT 'Protected' spec so that
    (toOpenApi protectedSpec
            -- there's a common components section that defines 'myJWT' security scheme under "jwtToken" name
            & components . securitySchemes . at "jwtToken" ?~ myJWT
            -- and all operations in this part of the spec are required to use "jwtToken" security scheme
            & allOperations . security .~ [SecurityRequirement $ mempty & at "jwtToken" ?~ []]
            -- and that implies that the endpoints could return 401 alongside normal responses defined elsewhere
            & canReturn401Response
    ) where
        myJWT                = SecurityScheme (SecuritySchemeHttp . HttpSchemeBearer . Just $ "jwt")
                                              (Just "jwt token")
        canReturn401Response = setResponse 401 (pure $ mempty & description .~ "Authorization failed")

```

I can see that the corresponding OpenAPI spec has properly associated the common `securitySchemes` section with endpoints' `security` sections, yet the interactive UI is still not sending the `Authorization` header when I fill it with a `Bearer <token>` value.

Is that because my endpoints are still using Servant's `Header "Authorization" JwtValue` combinators alongside OpenApi security definitions?
