### ISSUE TITLE
How to avoid logic duplication with manual `ToJSON` instance?

### ISSUE THREAD

**Issue by waalge** [biocad/openapi3#52]
If i derive my instances of `ToJSON` and `ToSchema`, then they play nice.
However the JSON is not fit for its intended purpose.

If I manually make an instance of `ToJSON`, is there anyway I can avoid having to write analogous logic for `ToSchema`.

The only solution I see is to write an intermediary data type with which deriving gives a desired result, 
and write the `to` and `from` functions between the original and intermediary type. 
Have I missed something? Is there a more idiomatic way?

**Comment by davidkraus** [comment]
@waalge did you find a solution to this?

**Comment by waalge** [comment]
Not really, 
I came to the conclusion that more typing of fundamental types with new types and use of the intermediate data types (which has the other advantage of being more immediate to parse - as a human) and then using the customizable deriving (eg `genericDeclareNamedSchema`) was good enough. 

I guessed that if you need an even greater handle on the schema, then the api is probably stable enough to warrant the overhead.
