### ISSUE TITLE
Haddock link to documentation is broken in the Readme.

### ISSUE THREAD

**Issue by mmzx** [biocad/openapi3#6]
The Readme explains the package is available on hackage:

-- | _Please refer to [haddock documentation](http://hackage.haskell.org/package/openapi3)._

However the link is broken, perhaps due to the fact that the package itself isn't available yet. I would be happy to help out if there is a challenge associated to this.

Perhaps related issue: #5 .

**Comment by maksbotan** [comment]
Uploaded, docs should be available soon :)

**Comment by mmzx** [comment]
Awesome, thanks a lot for this!
