### ISSUE TITLE
Exception when parsing newer OpenApi3 schemas

### ISSUE THREAD

**Issue by tonicebrian** [biocad/openapi3#64]
When parsing OpenApi **3.0.2** schemas like the [Pet Store api](https://petstore3.swagger.io/api/v3/openapi.json) with:

`eitherDecodeFileStrict openApiFile :: IO (Either String OpenApi)`

I get an exception:

```
"Error in $: Additonal field don't match for key openapi: String "3.0.0" /= String "3.0.2""
```

This is so because in https://github.com/biocad/openapi3/blob/master/src/Data/OpenApi/Internal/AesonUtils.hs#L199-L205 the check is testing for equality on the version defined in https://github.com/biocad/openapi3/blob/master/src/Data/OpenApi/Internal.hs#L1595, so newer versions like latest **3.0.3** will fail when reading. 

I thought on submitting a PR where we check for a regular expression instead of hard equality but I don't know about implications. Is this the way to go or would you approach the resolution differently?

**Comment by maksbotan** [comment]
Well, this library is based on 3.0.0 spec. If we were to support newer versions, I'd have to review them for potential differences.

Are you sure that the spec is at least backwards-compatible?

**Comment by tonicebrian** [comment]
Yes I think it is backwards compatible. 

- **3.0.1** although not explicitly stated I think there is no breaking changes [in the description](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.1)
- **3.0.2** says in the [release notes](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.2) _None of these modifications change the behavior of the spec_. 
- **3.0.3** says in the [release notes](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.3) _None of these modifications change the behavior of the spec_.

Also they bumped the patch version in the semver so theoretically it should be backwards compatible.

**Comment by maksbotan** [comment]
Ah, so the changes are only to the spec _text_, not to semantics? 

Could you make a PR allowing all 3.0.x versions then?

**Comment by tonicebrian** [comment]
Hey @maksbotan did you have a look at the PR? Is it OK for you?
